### PR TITLE
Update to Agda 2.6.4 and stdlib 2.0

### PR DESCRIPTION
**Pull request by jkopanski**
In order to do so I've set nixpkgs to current realese-23.11 branch. This also included update in ghc used in nixpkgs.

I've also added a python to the shell so it has everything that is needed to run commands in the README.

### CODE REVIEW

**Review by isovector — APPROVED** [review]
I don't pretend to understand nix, but CI is green and that's good enough for me.

**Comment by bolt12** [comment]
I took a look at it and looks good to me!

**Comment by bsaul** [comment]
This looks good to me. 

On a related note, I give a 👍🏼 to @VictorCMiraldo suggestion on discord to use flakes, though that should be a separate PR.

**Comment by jkopanski** [comment]
Made some more changes as I've noticed standard library files get copied. In order to copy proper version I went ahead and override it in the package set.

**Comment by bolt12** [comment]
I think you forgot to add a file

**Pull request merged**
